# Linkerd Control Plane Configuration for AI Fusion Core
# This file defines the core Linkerd components

apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-controller
  namespace: linkerd
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: Linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controller
        app.kubernetes.io/part-of: Linkerd
      annotations:
        config.linkerd.io/default-inbound-policy: "all-authenticated"
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: public-api
        image: gcr.io/linkerd-io/controller:stable-2.14.0
        ports:
        - containerPort: 8085
          name: grpc
        - containerPort: 9995
          name: admin-http
        env:
        - name: LINKERD2_PROXY_LOG
          value: "warn,linkerd=info"
        - name: LINKERD2_PROXY_LOG_FORMAT
          value: "plain"
        - name: LINKERD2_PROXY_DESTINATION_SVC_ADDR
          value: "localhost.:8086"
        - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
          value: "svc.cluster.local."
        - name: LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT
          value: "100ms"
        - name: LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT
          value: "1000ms"
        - name: LINKERD2_PROXY_CONTROL_LISTEN_ADDR
          value: "0.0.0.0:4190"
        - name: LINKERD2_PROXY_ADMIN_LISTEN_ADDR
          value: "0.0.0.0:4191"
        - name: LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR
          value: "127.0.0.1:4140"
        - name: LINKERD2_PROXY_INBOUND_LISTEN_ADDR
          value: "0.0.0.0:4143"
        - name: LINKERD2_PROXY_DESTINATION_GET_SUFFIXES
          value: "svc.cluster.local."
        - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
          value: "svc.cluster.local."
        - name: LINKERD2_PROXY_POLICY_SVC_ADDR
          value: "localhost.:8090"
        - name: LINKERD2_PROXY_POLICY_WORKLOAD
          value: "$(_pod_ns):$(_pod_name)"
        - name: LINKERD2_PROXY_INBOUND_DEFAULT_POLICY
          value: "all-authenticated"
        - name: LINKERD2_PROXY_POLICY_CLUSTER_NETWORKS
          value: "10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16"
        - name: LINKERD2_PROXY_IDENTITY_DIR
          value: "/var/run/linkerd/identity/end-entity"
        - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: |
            -----BEGIN CERTIFICATE-----
            MIIBYjCCAQugAwIBAgIBATAKBggqhkjOPQQDAjAYMRYwFAYDVQQHEw1V
            ...
            -----END CERTIFICATE-----
        - name: LINKERD2_PROXY_IDENTITY_TOKEN_FILE
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: LINKERD2_PROXY_IDENTITY_SVC_ADDR
          value: "localhost.:8080"
        - name: _pod_sa
          valueFrom:
            fieldRef:
              fieldPath: "spec.serviceAccountName"
        - name: _pod_ns
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: _pod_name
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: LINKERD2_PROXY_DESTINATION_CONTEXT
          value: |
            {"ns":"$(_pod_ns)", "nodeName":"$(_pod_nodeName)", "pod":"$(_pod_name)"}
        livenessProbe:
          httpGet:
            path: /live
            port: admin-http
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: admin-http
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-controller-api
  namespace: linkerd
  labels:
    app.kubernetes.io/name: controller-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: controller
  ports:
  - name: grpc
    port: 8085
    targetPort: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-destination
  namespace: linkerd
  labels:
    app.kubernetes.io/name: destination
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: destination
  template:
    metadata:
      labels:
        app.kubernetes.io/name: destination
      annotations:
        config.linkerd.io/default-inbound-policy: "all-authenticated"
    spec:
      containers:
      - name: destination
        image: gcr.io/linkerd-io/controller:stable-2.14.0
        ports:
        - containerPort: 8086
          name: grpc
        - containerPort: 9996
          name: admin-http
        env:
        - name: LINKERD2_PROXY_LOG
          value: "warn,linkerd=info"
        - name: LINKERD2_PROXY_LOG_FORMAT
          value: "plain"
        - name: LINKERD2_PROXY_DESTINATION_SVC_ADDR
          value: "localhost.:8086"
        - name: LINKERD2_PROXY_CONTROL_LISTEN_ADDR
          value: "0.0.0.0:4190"
        - name: LINKERD2_PROXY_ADMIN_LISTEN_ADDR
          value: "0.0.0.0:4191"
        - name: LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR
          value: "127.0.0.1:4140"
        - name: LINKERD2_PROXY_INBOUND_LISTEN_ADDR
          value: "0.0.0.0:4143"
        livenessProbe:
          httpGet:
            path: /live
            port: admin-http
        readinessProbe:
          httpGet:
            path: /ready
            port: admin-http
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-destination
  namespace: linkerd
  labels:
    app.kubernetes.io/name: destination
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: destination
  ports:
  - name: grpc
    port: 8086
    targetPort: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
  labels:
    app.kubernetes.io/name: proxy-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy-injector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy-injector
      annotations:
        config.linkerd.io/default-inbound-policy: "all-authenticated"
    spec:
      containers:
      - name: proxy-injector
        image: gcr.io/linkerd-io/controller:stable-2.14.0
        ports:
        - containerPort: 8443
          name: https
        - containerPort: 9990
          name: admin-http
        env:
        - name: LINKERD2_PROXY_LOG
          value: "warn,linkerd=info"
        - name: LINKERD2_PROXY_LOG_FORMAT
          value: "plain"
        livenessProbe:
          httpGet:
            path: /live
            port: admin-http
        readinessProbe:
          httpGet:
            path: /ready
            port: admin-http
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
  labels:
    app.kubernetes.io/name: proxy-injector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: proxy-injector
  ports:
  - name: https
    port: 443
    targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-identity
  namespace: linkerd
  labels:
    app.kubernetes.io/name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: identity
  template:
    metadata:
      labels:
        app.kubernetes.io/name: identity
      annotations:
        config.linkerd.io/default-inbound-policy: "all-authenticated"
    spec:
      containers:
      - name: identity
        image: gcr.io/linkerd-io/controller:stable-2.14.0
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 9990
          name: admin-http
        env:
        - name: LINKERD2_PROXY_LOG
          value: "warn,linkerd=info"
        - name: LINKERD2_PROXY_LOG_FORMAT
          value: "plain"
        livenessProbe:
          httpGet:
            path: /live
            port: admin-http
        readinessProbe:
          httpGet:
            path: /ready
            port: admin-http
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-identity
  namespace: linkerd
  labels:
    app.kubernetes.io/name: identity
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: identity
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc